<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title></title>
    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="./js/usershow/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="./css/usershow/reset.css" />
<link rel="stylesheet" type="text/css" href="./css/usershow/common.css" />
<style>
#main{width:55%; margin:auto; margin-top:15px; min-height:400px; background-image:url(/skin/jiayinji/images/show_news_bg.png); margin-bottom:20px;}

#main_left{width:720px; float:left; margin-left:20px;}
#main_left h1{ color:#962653; font-size:36px; font-weight:bold;}
#main_left .menu{height:18px; margin:6px 0 4px 0; display:block; line-height:18px;}
#main_left .menu cite{float:left; display:block; background-image:url(/skin/jiayinji/images/about_news_01.png); padding-left:24px; background-repeat:no-repeat; font-size:14px; padding-right:20px; font-style:normal;}
#main_left .menu em{float:left; display:block; background-image:url(/skin/jiayinji/images/about_news_02.png); padding-left:24px; background-repeat:no-repeat; font-size:14px; font-style:normal;}

#main_left .body{margin:12px 0;}

#main_left .body img{
    max-width:720px;
	width:expression(document.body.clientWidth > 720? "720px": "auto" );
	height:auto;
}

#main_right{width:219px; float:right; margin-right:20px;}

#main_right ul li img{width:219px; height:100px; margin-bottom:5px; border:0;}
</style>

  </head>
  
  <body>    <!-- ****************************head******************************* -->
   <s:url action="cancelAction" namespace="/login" var="cancel"/>
<s:url action="memberAction" namespace="/login" var="member"/>
	<div class="top">
    	<div class="topcon">
        	<div class="welcome">欢迎访问名流影像馆！</div>
            <s:if test="%{#request.session.usermain==null}">
            <div class="loginreg"><a href="login.jsp">登陆</a> <a href="#">注册</a></div>
            </s:if>
            <s:else><div class="loginreg"><a href='<s:property value="member"/>'><s:property value="%{#request.session.usermain.username }"/></a> <a href='<s:property value="cancel"/>'>注销</a></div></s:else>
            <div class="logo"><a href=""><img src="images/logo.png" border="none" width="134" height="78" /></a></div>
        </div>
    </div>
  <div class="navi">
    	<ul>
        	<li><a href="index.jsp">首页</a></li>
            <li><a href="jiayinji.jsp">家印记</a></li>
            <li><a href="active.jsp">最新活动</a></li>
            <li><a href="yuepai.jsp">定制约拍</a></li>
            <li><a href="shop.jsp">网络商城</a></li>
            <li><a href="usershow.jsp">客照展示</a></li>
            <li><a href="contactus.jsp">联系我们</a></li>
            <li><a href='<s:property value="member"/>'>会员服务</a></li>
        </ul>
    </div>
    <!-- ***************************************************************** -->
    		<div id="main">
	<div id="main_left">
		<h1>幸福很简单，一个温暖的怀抱，一个可靠的肩膀</h1>
		<p class="menu">
			<cite></cite>
			<em>2015-01-26 15:06:05</em>
		</p>
		<div class="body">
<p>&nbsp;<span style="font-family: 宋体; color: rgb(62, 62, 62); font-size: 15.1999998092651px; line-height: 19.2000007629395px; white-space: pre-wrap;">再有钱的男人也比不上一个知冷知热疼你的男人重要，再多的爱马仕也抵不过，每天早晨跑几条街为你买豆浆油条的幸福，再好的甜言蜜语也不如你需要时陪在身边肩并肩的相伴 ，世界上最奢侈的人，是肯花时间陪你的人，对的人总会遇到，无论在哪里！</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="./images/jiayinji/news/2/6e153c6970cd254d4e0bf086f289fb76.jpg" alt="11111.jpg" width="400" height="400" /></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">风景在美，若没人一起欣赏，也会有种莫名的忧伤。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">再好的生活，若没人一起分享，也会有种莫名的凄凉。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">再坏的处境，若有人陪伴，也会有莫名的感动。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">再苦的日子，若有人相伴，也会有莫名的幸福！</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
幸福很简单，一个温暖的怀抱，一个可靠的肩膀</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">幸福是一种感觉，和贫富无关，爱情不用唯美浪漫，不用惊天动地，就是左手牵右手，不离不弃，不变不移！</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">钱固然重要，但只是生活需要。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">只要有双勤劳的双手，多少都可以挣，而爱人，错过了，就再也找不回来。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">有钱，是物质的满足，幸福，是精神上的满足。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
真情，不用钱买，真心，钱更买不到。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">女人长的漂亮，不如活的漂亮，有钱花，不如有人疼！</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">幸福很简单，一个温暖的怀抱，一个可靠的肩膀！</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">被恨的人没有痛苦，恨人的人却终将遍体鳞伤，所以，从此，绝不去恨人。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
缘分是本书，翻得不经意会错过，读得太认真会流泪。 </span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">不同傻子争辩，否则就搞不清谁是傻子了。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">学历是铜牌，能力是银牌，人脉是金牌，思维是王牌。成功的人不是赢在起点，而是赢在转折点。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">钱有两种：花掉的是钱，叫财产;没花掉的是&ldquo;纸&rdquo;，叫遗产。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="./images/jiayinji/news/2/c86e96886fa94ef360e2d04cf8d34c27.jpg" alt="112222.jpg" width="500" height="330" /></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">真正的强者，不是没有眼泪的人，而是含着眼泪依然微笑，依然奔跑的人!</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">生命中，很多事是事在人为。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">生活中，总让人不知所措。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">生活中，不要轻易为别人而改变自己。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">任何时候，都不要失去了自己！</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
人生，只能越来越简单。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">人生，其实就是不断地面对，不断的选择，不断的放弃。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">这个世界最坏罪名，叫做太易动情。赢的人一直赢，输的人输到底。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; color: rgb(255, 0, 0); box-sizing: border-box !important; word-wrap: break-word !important;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">不要轻易去依赖一个人，它会成为你的习惯，当分别来临，你失去的不是某个人，而是你精神的拐杖。</span></strong></span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">生命太短，没有时间留给遗憾，若不是终点，请微笑一直向前。<br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><img src="./images/jiayinji/news/2/8a1c1f5213a37111826f349ee50dcbc9.jpg" alt="333333.jpg" width="500" height="330" /></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
拥有一颗心，永远柔软，一种脾性，永不疲惫，一种触摸，永无伤害。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">请对梦想充满信心，总有一天属于你的彩虹会在天空微笑。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">主动久了会很累， 在乎久了会崩溃。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">无论是在爱情还是友情里，我们都是没有安全感的人，因为太在意，我们都害怕失去。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;"><br style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;" />
有些事情，不谈是个结，谈开了是个疤。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">人一生中会遇到不顺心的事，会碰到不顺眼的人，如果你不学会原谅，就会活得痛苦，活得累。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">请不要旁听生命，从现在起就去展示和做最好的自己。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">朋友不是先来的人或者认识最久的人，而是那个来了以后再也没有走的人。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; line-height: 19.2000007629395px; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; font-family: 宋体; box-sizing: border-box !important; word-wrap: break-word !important;">有时候，你需要做的就是闭嘴，放下所谓的自尊，承认自己的错误。这不叫放弃，而叫成长。</span></p>		</div>
	</div>
	
	<div style="clear:both"></div>
</div>

    
    <!-- ****************************foot******************************* -->
    <div class="footer">
    	<div class="foocon">
            <div class="banquan">
                <a href="jiayinji.jsp">关于我们</a> | <a href="#">常见问题</a> | <a href="#">法律声明</a> | <a href="contactus.jsp">联系我们</a><br />
    Copyright © 2003-2015名流家印记 All Rights Reserved
            </div>
            <div class="link">
            	<a href="javascript:void(0)" id="wx"><img src="images/weixin.png" border="none" width="36" height="33" /></a>
                <a href="#"><img src="images/weibo.png" border="none" width="40" height="33" /></a>
                <a href="#"><img src="images/qq.png" border="none" width="30" height="32" /></a>
            </div>
        </div>
    </div>
    <div class="erweima" id="ewm"><img src="images/erweima.jpg" width="200" height="200" /></div>
    <script>
    $("#wx").hover(function() {
        $(".erweima").show();
    }, function() {
    $(".erweima").hide();
    });</script>
  </body>
</html>
