<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib uri="/struts-tags" prefix="s"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title></title>
    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="./js/usershow/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="./css/usershow/reset.css" />
<link rel="stylesheet" type="text/css" href="./css/usershow/common.css" />
<style>
#main{width:55%; margin:auto; margin-top:15px; min-height:400px; background-image:url(/skin/jiayinji/images/show_news_bg.png); margin-bottom:20px;}

#main_left{width:720px; float:left; margin-left:20px;}
#main_left h1{ color:#962653; font-size:36px; font-weight:bold;}
#main_left .menu{height:18px; margin:6px 0 4px 0; display:block; line-height:18px;}
#main_left .menu cite{float:left; display:block; background-image:url(/skin/jiayinji/images/about_news_01.png); padding-left:24px; background-repeat:no-repeat; font-size:14px; padding-right:20px; font-style:normal;}
#main_left .menu em{float:left; display:block; background-image:url(/skin/jiayinji/images/about_news_02.png); padding-left:24px; background-repeat:no-repeat; font-size:14px; font-style:normal;}

#main_left .body{margin:12px 0;}

#main_left .body img{
    max-width:720px;
	width:expression(document.body.clientWidth > 720? "720px": "auto" );
	height:auto;
}

#main_right{width:219px; float:right; margin-right:20px;}

#main_right ul li img{width:219px; height:100px; margin-bottom:5px; border:0;}
</style>

  </head>
  
  <body>    <!-- ****************************head******************************* -->
   <s:url action="cancelAction" namespace="/login" var="cancel"/>
<s:url action="memberAction" namespace="/login" var="member"/>
	<div class="top">
    	<div class="topcon">
        	<div class="welcome">欢迎访问名流影像馆！</div>
            <s:if test="%{#request.session.usermain==null}">
            <div class="loginreg"><a href="login.jsp">登陆</a> <a href="#">注册</a></div>
            </s:if>
            <s:else><div class="loginreg"><a href='<s:property value="member"/>'><s:property value="%{#request.session.usermain.username }"/></a> <a href='<s:property value="cancel"/>'>注销</a></div></s:else>
            <div class="logo"><a href=""><img src="images/logo.png" border="none" width="134" height="78" /></a></div>
        </div>
    </div>
    <div class="navi">
    	<ul>
        	<li><a href="index.jsp">首页</a></li>
            <li><a href="jiayinji.jsp">家印记</a></li>
            <li><a href="active.jsp">最新活动</a></li>
            <li><a href="yuepai.jsp">定制约拍</a></li>
            <li><a href="shop.jsp">网络商城</a></li>
            <li><a href="usershow.jsp">客照展示</a></li>
            <li><a href="contactus.jsp">联系我们</a></li>
            <li><a href='<s:property value="member"/>'>会员服务</a></li>
        </ul>
    </div>
    <!-- ***************************************************************** -->
   <div id="main">
	<div id="main_left">
		<h1>原创歌曲【爱的天使】——家印记主题歌</h1>
		<p class="menu">
			<cite></cite>
			<em>2015-01-11 13:34:24</em>
		</p>
		<div class="body">

<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"> </span><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"> </span></span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">每一天</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">我们展开双臂</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">迎接你</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">也拥抱自己</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">我的家</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">永远都在这里</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">因为爱</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">我们相聚一起</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;"> </span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">我愿意</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">所以我会真心</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">就像你</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">会为爱去坚信</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">能相遇</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">是缘分的旨意</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">因为爱</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">我们永不分离</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;"> </span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">爱的天使</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">播洒着温馨</span></span><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;"> </span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">闪光下 梦会更清晰</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">把家的印记</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">和幸福传递</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">每一天都有新的奇迹</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">新的奇迹</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;"> </span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">爱的天使</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">有我的名字</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">手牵手 一起去耕耘</span></span><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;"> </span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">让爱的意义</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">变成永恒的主题</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">让我们分享幸福与甜蜜</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 宋体; font-size: 16px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; max-width: 100%; color: rgb(0, 112, 192); box-sizing: border-box !important; word-wrap: break-word !important;">幸福与甜蜜</span></span></p>
<p style="margin: 0px; padding: 0px; border: none; outline: 0px; font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans GB', 'Microsoft YaHei', &Icirc;&cent;&Egrave;&iacute;&Ntilde;&Aring;&ordm;&Uacute;, Arial, sans-serif; font-size: 15.1999998092651px; font-stretch: inherit; line-height: 19.2000007629395px; vertical-align: baseline; max-width: 100%; clear: both; min-height: 1em; white-space: pre-wrap; color: rgb(62, 62, 62); box-sizing: border-box !important; word-wrap: break-word !important;">&nbsp;</p>
</div>
	
	<div style="clear:both"></div>
</div>

</div>


    
    <!-- ****************************foot******************************* -->
    <div class="footer">
    	<div class="foocon">
            <div class="banquan">
                <a href="jiayinji.jsp">关于我们</a> | <a href="#">常见问题</a> | <a href="#">法律声明</a> | <a href="contactus.jsp">联系我们</a><br />
    Copyright © 2003-2015名流家印记 All Rights Reserved
            </div>
            <div class="link">
            	<a href="javascript:void(0)" id="wx"><img src="images/weixin.png" border="none" width="36" height="33" /></a>
                <a href="#"><img src="images/weibo.png" border="none" width="40" height="33" /></a>
                <a href="#"><img src="images/qq.png" border="none" width="30" height="32" /></a>
            </div>
        </div>
    </div>
    <div class="erweima" id="ewm"><img src="images/erweima.jpg" width="200" height="200" /></div>
    <script>
    $("#wx").hover(function() {
        $(".erweima").show();
    }, function() {
    $(".erweima").hide();
    });</script>
  </body>
</html>
